headlamp:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: private-ca-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure # don't allow http
      traefik.ingress.kubernetes.io/router.tls: "true" # not needed when "tls" section is used
    hosts:
      - host: headlamp.MY_SERVER.MY_IP.sslip.io
        paths:
          - path: "/"
            type: Prefix
    tls:
      - hosts:
          - headlamp.MY_SERVER.MY_IP.sslip.io
        secretName: headlamp-tls
