headlamp:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: private-ca-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure # don't allow http
      traefik.ingress.kubernetes.io/router.tls: "true" # not needed when "tls" section is used
    hosts:
      - host: headlamp.um3.172.19.112.42.sslip.io
        paths:
          - path: "/"
            type: Prefix
    tls:
      - hosts:
          - headlamp.um3.172.19.112.42.sslip.io
        secretName: headlamp-tls

  config:
    inCluster: true
    extraArgs:
      - "-oidc-ca-file=/usr/share/nginx/html/private-root-ca.crt"
      # - "-oidc-skip-tls-verify" # fixed error: 'x509: certificate signed by unknown authority'
    oidc:
      useAccessToken: false
      # secret:
      #   create: false
      clientID: headlamp
      clientSecret: headlamp-secret
      # issuerURL: http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/realms/homelab
      issuerURL: https://keycloak.um3.172.19.112.42.sslip.io/auth/realms/homelab

      # callbackURL: https://headlamp.um3.172.19.112.42.sslip.io/oidc-callback
      # validatorIssuerURL: https://keycloak.um3.172.19.112.42.sslip.io/auth/realms/homelab
      validatorClientID: headlamp
      scopes: "openid,profile,email"
      # scopes: "profile email offline_access"

# Copy from cert-manager and mount to fix tls-verify issue
# k get secret -n cert-manager private-root-ca-secret -o yaml > ca-sec.yaml
  volumeMounts:
    - name: ca
      mountPath: /usr/share/nginx/html/private-root-ca.crt
      subPath: ca.crt
      readOnly: true
  volumes:
    - name: ca
      secret:
        secretName: private-root-ca-secret
