  jupyterhub:
    ingress:
      enabled: true
      hosts: ['jupyterhub.MY_SERVER.MY_IP.sslip.io']
      annotations:
        cert-manager.io/cluster-issuer: private-ca-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      tls:
      - hosts:
          - jupyterhub.MY_SERVER.MY_IP.sslip.io
        secretName: jupyterhub-tls
    hub:
      config:
        JupyterHub:
          admin_access: true
          authenticator_class: generic-oauth

        GenericOAuthenticator:
          client_id: jupyterhub
          client_secret: jupyterhub-secret
          token_endpoint_auth_method: client_secret_post
          validate_server_cert: false # when running without valid https cert
          oauth_callback_url: https://jupyterhub.MY_SERVER.MY_IP.sslip.io/hub/oauth_callback

          authorize_url: https://keycloak.MY_SERVER.MY_IP.sslip.io/auth/realms/homelab/protocol/openid-connect/auth
          token_url: https://keycloak.MY_SERVER.MY_IP.sslip.io/auth/realms/homelab/protocol/openid-connect/token
          userdata_url: https://keycloak.MY_SERVER.MY_IP.sslip.io/auth/realms/homelab/protocol/openid-connect/userinfo
          logout_redirect_url: https://keycloak.MY_SERVER.MY_IP.sslip.io/auth/realms/homelab/protocol/openid-connect/logout
          
          scope:
            - openid
            - profile
            - email

          username_claim: preferred_username
          userdata_method: GET

          allowed_users:
            - josef
            - lee
          admin_users:
            - josef

      extraEnv:
        OAUTH2_AUTHORIZE_URL: https://keycloak.MY_SERVER.MY_IP.sslip.io/realms/homelab/protocol/openid-connect/auth
        OAUTH2_TOKEN_URL: https://keycloak.MY_SERVER.MY_IP.sslip.io/realms/homelab/protocol/openid-connect/token
