ingress:
  enabled: true
  host:  k0rdent-catalog-web.MY_SERVER.MY_IP.sslip.io
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    - secretName: grafana-tls
      hosts: ['k0rdent-catalog-web.MY_SERVER.MY_IP.sslip.io']
