postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: keycloak-user
    database: keycloak-db
    # postgresPassword: ''
    # password: ''
    existingSecret: keycloak-auth
    secretKeys:
      adminPasswordKey: postgresPassword
      userPasswordKey: dbPassword
  readReplicas:
    replicaCount: 2
