keycloakx:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: private-ca-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure # don't allow http
      traefik.ingress.kubernetes.io/router.tls: "true" # not needed when "tls" section is used
    rules:
      - host: keycloak.MY_SERVER.MY_IP.sslip.io
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - hosts:
          - keycloak.MY_SERVER.MY_IP.sslip.io
        secretName: keycloak-tls
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--proxy-headers=xforwarded"

  extraEnv: |
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-auth
          key: keycloakAdminUserPassword
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query=keycloakx-headless
        -Dkeycloak.migration.action=import
        -Dkeycloak.migration.provider=dir
        -Dkeycloak.migration.dir=/opt/keycloak/data/import
        -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
        -Dkeycloak.migration.replace-placeholders=true

  dbchecker:
    enabled: true

  database:
    vendor: postgres
    hostname: keycloak-pg-postgresql.keycloak.svc.cluster.local
    port: 5432
    username: keycloak-user
    # password: ''
    database: keycloak-db
    existingSecret: keycloak-auth
    existingSecretKey: dbPassword

  extraVolumes: |
    - name: realm-config
      configMap:
        name: keycloak-realm

  extraVolumeMounts: |
    - name: realm-config
      mountPath: /opt/keycloak/data/import
      readOnly: true
