raw:
  resources:
  # Keycloak secrets database secrets
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-auth
    type: Opaque
    stringData:
      postgresPassword: mainPasswd
      dbPassword: keycloakPasswd
      keycloakAdminUserPassword: Key.Admin1

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: keycloak-realm
      namespace: keycloak
    data:
      homelab-realm.json: |
        {
          "realm": "homelab",
          "enabled": true,
          "users": [
            {
              "username": "josef",
              "enabled": true,
              "email": "josef@example.com",
              "groups": ["k8s-admins"],
              "firstName": "Josef",
              "lastName": "Hak",
              "emailVerified": true,
              "credentials": [
                {
                  "type": "password",
                  "value": "CHANGE_ME",
                  "temporary": true
                }
              ]
            },
            {
              "username": "lee",
              "enabled": true,
              "email": "lxie@example.com",
              "groups": ["k8s-readonly"],
              "firstName": "Lee",
              "lastName": "Xie",
              "emailVerified": true,
              "credentials": [
                {
                  "type": "password",
                  "value": "CHANGE_ME",
                  "temporary": true
                }
              ]
            }
          ],
          "groups": [
            {"name": "k8s-admins"},
            {"name": "k8s-readonly"}
          ],
          "clients": [
            {
              "clientId": "grafana",
              "enabled": true,
              "publicClient": false,
              "redirectUris": [
                "https://grafana.172.19.112.42.sslip.io/login/generic_oauth"
              ],
              "protocol": "openid-connect",
              "secret": "grafana-secret"
            },
            {
              "clientId": "jupyterhub",
              "enabled": true,
              "protocol": "openid-connect",
              "publicClient": false,
              "secret": "jupyterhub-secret",
              "redirectUris": [
                "https://jupyterhub.um3.172.19.112.42.sslip.io/hub/oauth_callback"
              ],
              "webOrigins": [
                "https://jupyterhub.um3.172.19.112.42.sslip.io"
              ],
              "standardFlowEnabled": true,
              "directAccessGrantsEnabled": false
            },
            {
              "clientId": "headlamp",
              "enabled": true,
              "protocol": "openid-connect",
              "publicClient": false,
              "secret": "headlamp-secret",
              "redirectUris": [
                "https://headlamp.um3.172.19.112.42.sslip.io/oidc-callback"
              ],
              "webOrigins": [
                "https://headlamp.um3.172.19.112.42.sslip.io"
              ],
              "standardFlowEnabled": true,
              "directAccessGrantsEnabled": false
            }
          ]
        }
