raw:
  resources:
  # Keycloak secrets database secrets
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-auth
    type: Opaque
    stringData:
      postgresPassword: mainPasswd
      dbPassword: keycloakPasswd
      keycloakAdminUserPassword: Key.Admin1

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: keycloak-realm
      namespace: keycloak
    data:
      homelab-realm.json: |
        {
          "realm": "homelab",
          "enabled": true,
          "clients": [
            {
              "clientId": "grafana",
              "enabled": true,
              "publicClient": false,
              "redirectUris": [
                "https://grafana.172.19.112.42.sslip.io/login/generic_oauth"
              ],
              "protocol": "openid-connect",
              "secret": "grafana-secret"
            }
          ]
        }