raw:
  resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: keycloak-db
    type: Opaque
    stringData:
      postgresPassword: mainPasswd
      dbPassword: keycloakPasswd
      keycloakAdminUserPassword: Key.Admin1
