traefik:
  deployment:
    kind: DaemonSet

  ports:
    web:
      port: 8000
      hostPort: 80
    websecure:
      port: 8443
      hostPort: 443

  additionalArguments:
    - "--entrypoints.web.http.redirections.entrypoint.to=:443"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    - "--entrypoints.web.http.redirections.entrypoint.permanent=true"

  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enabled: true
        namespace: traefik
        interval: 30s
        additionalLabels:
          release: grafana
      addEntryPointsLabels: true
      addRoutersLabels: true
      addServicesLabels: true
